feature_extractor:
    model_path: "efficientnet_b1"
    representation_size: 512

transformer:
    feedforward_size: 1024
    transformer_output_size: 784
    num_attention_heads: 4
    num_encoder_layers: 2
    output_size: 1024
    dropout_rate: 0.1

heads:
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 9
            loss_weight: 0
        hand_shape_base_form:
            num_class: 12
            loss_weight: 0.5
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 0.5
        hand_shape_bending:
            num_class: 6
            loss_weight: 0
        hand_position_finger_direction:
            num_class: 18
            loss_weight: 0
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 0
        hand_location_x:
            num_class: 5
            loss_weight: 0
        hand_location_y:
            num_class: 37
            loss_weight: 0
