feature_extractor:
    model_path: "efficientnet_b1"
    representation_size: 384

transformer:
    feedforward_size: 384
    transformer_output_size: -5
    num_attention_heads: 6
    num_encoder_layers: 2
    output_size: 384
    dropout_rate: 0.2

heads:
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 9
            loss_weight: 1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 1
        hand_shape_bending:
            num_class: 6
            loss_weight: 1
        hand_position_finger_direction:
            num_class: 18
            loss_weight: 1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 1
        hand_location_x:
            num_class: 5
            loss_weight: 1
        hand_location_y:
            num_class: 37
            loss_weight: 1

freeze_scheduler:
    model_params:
        feature_extractor: [True, False, True, False, True, False, True, False, True, False, True]
        transformer: [False, True, False, True, False, True, False, True, False, True, False]
    freeze_pattern_repeats: [200, 50, 200, 50, 200, 50, 200, 50, 200, 50, 10000]
    freeze_mode: "step"
    verbose: False
