general_parameters:
    data_paths: ["/dih4/dih4_2/hearai/nczerep/pjm-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/basiclexicon-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/galex-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/glex-keyframes/"]
    ratio_train_test: 0.8
    workers: 0
    gpu: -1
    path_to_save: "saved_model.pth"
    seed: 2021
    neptune: False

augmentations_parameters:
    apply_resize: True
    apply_center_crop: True
    apply_random_erasing: False
    apply_random_rotation: False
    apply_color_jitter: False

    resize_size: 256
    center_crop_size: 256
    random_erasing_probability: 0.5
    random_rotation_degree: 5
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05

train_parameters:
    classification_mode: "hamnosys"
    epochs: 10
    batch_size: 2
    lr: 0.0003
    num_segments: 20
    fast_dev_run: False
    pre_training: False
    use_frames: True
    use_landmarks: False
    time: null
    warmup_steps: 20.0
    multiply_lr_step: 0.95

feature_extractor:
    name: "cnn_extractor"
    model_path: "efficientnet_b1"
    representation_size: 1024

transformer:
    name: "sign_language_transformer"
    feedforward_size: 1024
    num_attention_heads: 4
    num_encoder_layers: 2
    output_size: 512
    dropout_rate: 0.2

heads:
    model:
        additional_layers: 0
        dropout_rate: 0.1
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 9
            loss_weight: 0.1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 0.3
        hand_shape_bending:
            num_class: 6
            loss_weight: 0.1
        hand_position_finger_direction:
            num_class: 18
            loss_weight: 0.1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 0.1
        hand_location_x:
            num_class: 5
            loss_weight: 0.1
        hand_location_y:
            num_class: 37
            loss_weight: 0.1

freeze_scheduler:
    model_params:
        feature_extractor: [True]
        transformer: [False]
    freeze_pattern_repeats: [1600]
    freeze_mode: "step"
    verbose: False
