general_parameters:
    data_paths: ["/media/data512/hearai/frames/pjm", "/media/data512/hearai/frames/basic_lexicon", "/media/data512/hearai/frames/galex", "/media/data512/hearai/frames/glex"]
    ratio_train_test: 0.8
    workers: 16
    gpu: 0
    path_to_save: "saved_model.pth"
    seed: 2021
    neptune: True

augmentations_parameters:
    apply_resize: True
    apply_center_crop: True
    apply_random_erasing: False
    apply_random_rotation: False
    apply_color_jitter: False

    resize_size: 256
    center_crop_size: 256
    random_erasing_probability: 0.5
    random_rotation_degree: 5
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05

train_parameters:
    classification_mode: "hamnosys"
    epochs: 10000
    batch_size: 16
    lr: 0.001
    num_segments: 32
    fast_dev_run: False
    pre_training: False
    use_frames: False
    use_landmarks: True
    time: 0.1
    warmup_steps: 5000.0
    multiply_lr_step: 1

feature_extractor:
    name: "cnn_extractor"
    model_path: "efficientnet_b1"
    representation_size: 64

transformer:
    name: "sign_language_cnn_transformer"
    feedforward_size: 64
    num_attention_heads: 1
    num_encoder_layers: 4
    output_size: 64
    dropout_rate: 0.2

heads:
    model:
        additional_layers: 3
        dropout_rate: 0.3
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 3
            loss_weight: 1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 1
        hand_shape_bending:
            num_class: 2
            loss_weight: 1
        hand_position_finger_direction:
            num_class: 9
            loss_weight: 1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 1
        hand_location_x:
            num_class: 3
            loss_weight: 1
        hand_location_y:
            num_class: 15
            loss_weight: 1

freeze_scheduler:
    model_params:
        feature_extractor: [False]
        transformer: [False]
    freeze_pattern_repeats: [1]
    freeze_mode: "step"
    verbose: False
