general_parameters:
    data_paths: ["/dih4/dih4_2/hearai/training_data/keyframes/basic_lexicon_keyframes", "/dih4/dih4_2/hearai/training_data/keyframes/galex_keyframes", "/dih4/dih4_2/hearai/training_data/keyframes/glex_keyframes", "/dih4/dih4_2/hearai/training_data/keyframes/pjm_keyframes", "/dih4/dih4_2/hearai/training_data/keyframes/gsll_keyframes"]
    ratio_train_test: 0.8
    workers: 8
    gpu: 0
    path_to_save: "model.pth"
    seed: 2021
    neptune: True

augmentations_parameters:
    apply_resize: True
    apply_center_crop: True
    apply_random_erasing: False
    apply_random_rotation: True
    apply_color_jitter: False

    resize_size: 240
    center_crop_size: 224
    random_erasing_probability: 0
    random_rotation_degree: 10
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05

train_parameters:
    classification_mode: "hamnosys"
    epochs: 15
    batch_size: 8
    accumulate_grad_batches: 16
    lr: 0.0003
    num_segments: 20
    fast_dev_run: False
    pre_training: False
    landmarks: False
    time: null
    warmup_steps: 20.0
    multiply_lr_step: 0.95
    use_frames: True
    use_landmarks: False

feature_extractor:
    representation_size: 400

transformer: None

heads:
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 9
            loss_weight: 1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 1
        hand_shape_bending:
            num_class: 6
            loss_weight: 1
        hand_position_finger_direction:
            num_class: 18
            loss_weight: 1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 1
        hand_location_x:
            num_class: 5
            loss_weight: 1
        hand_location_y:
            num_class: 37
            loss_weight: 1

freeze_scheduler: None