general_parameters:
    data_paths: ["/dih4/dih4_2/hearai/nczerep/pjm-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/basiclexicon-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/galex-keyframes/",
                "/dih4/dih4_2/hearai/nczerep/glex-keyframes/"]
    ratio_train_test: 0.8
    workers: 16
    gpu: 0
    path_to_save: "saved_model.pth"
    seed: 2021
    neptune: True

augmentations_parameters:
    apply_resize: True
    apply_center_crop: True
    apply_random_erasing: False
    apply_random_rotation: True
    apply_color_jitter: True
    resize_size: 230
    center_crop_size: 224
    random_erasing_probability: 0.5
    random_rotation_degree: 5
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05

train_parameters:
    classification_mode: "hamnosys"
    epochs: 100
    batch_size: 8
    lr: 0.0001
    num_segments: 5
    fast_dev_run: False
    pre_training: False
    use_frames: True
    use_landmarks: True
    time: null
    warmup_steps: 20.0
    multiply_lr_step: 0.95
    accumulate_grad_batches: 8

feature_extractor:
    representation_size: 400
    load_pretrained: True

transformer:
    name: "sign_language_transformer"
    feedforward_size: 512
    num_attention_heads: 4
    num_encoder_layers: 2
    output_size: 400
    dropout_rate: 0.1

heads:
    model:
        additional_layers: 0
        dropout_rate: 0.1
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 3
            loss_weight: 1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 1
        hand_shape_bending:
            num_class: 2
            loss_weight: 1
        hand_position_finger_direction:
            num_class: 9
            loss_weight: 1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 1
        hand_location_x:
            num_class: 3
            loss_weight: 1
        hand_location_y:
            num_class: 15
            loss_weight: 1

freeze_scheduler:
    None
