augmentations:
    apply_resize: True
    apply_center_crop: True
    apply_random_erasing: False
    apply_random_rotation: False
    apply_color_jitter: False

    resize_size: 256
    center_crop_size: 256
    random_erasing_probability: 0.5
    random_rotation_degree: 5
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05

feature_extractor:
    model_path: "efficientnet_b1"
    representation_size: 600

transformer:
    feedforward_size: 600
    transformer_output_size: 600
    num_attention_heads: 4
    num_encoder_layers: 2
    output_size: 600
    dropout_rate: 0.2

heads:
    gloss:
        gloss:
            num_class: 2400
            loss_weight: 1
    hamnosys:
        symmetry_operator:
            num_class: 9
            loss_weight: 1
        hand_shape_base_form:
            num_class: 12
            loss_weight: 1
        hand_shape_thumb_position:
            num_class: 4
            loss_weight: 1
        hand_shape_bending:
            num_class: 6
            loss_weight: 1
        hand_position_finger_direction:
            num_class: 18
            loss_weight: 1
        hand_position_palm_orientation:
            num_class: 8
            loss_weight: 1
        hand_location_x:
            num_class: 5
            loss_weight: 1
        hand_location_y:
            num_class: 37
            loss_weight: 1

freeze_scheduler:
    model_params:
        feature_extractor: [True, False, True, False, True, False]
        transformer: [False, True, False, True, False, True]
    freeze_pattern_repeats: [200, 200, 200, 200, 200, 200]
    freeze_mode: "step"
    verbose: False
